import type { TrainingResource } from "../types";

export const TRAINING_CATALOG: TrainingResource[] = [
  {
    id: "training.contract-law-fundamentals",
    titleKey: "training.contractLawFundamentals.title",
    descriptionKey: "training.contractLawFundamentals.description",
    contentType: "book",
    productCodes: ["lro"],
    tags: ["contracts", "legal", "fundamentals"],
    estimatedMinutes: 45,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
  {
    id: "training.negotiation-strategies",
    titleKey: "training.negotiationStrategies.title",
    descriptionKey: "training.negotiationStrategies.description",
    contentType: "video",
    productCodes: ["lro"],
    tags: ["negotiation", "contracts", "strategy"],
    estimatedMinutes: 80,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
  {
    id: "training.ip-rights",
    titleKey: "training.ipRights.title",
    descriptionKey: "training.ipRights.description",
    contentType: "article",
    productCodes: ["lro"],
    tags: ["ip", "legal", "rights"],
    estimatedMinutes: 30,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
  {
    id: "training.digital-contract-management",
    titleKey: "training.digitalContractManagement.title",
    descriptionKey: "training.digitalContractManagement.description",
    contentType: "blog",
    productCodes: ["lro"],
    tags: ["digital", "management", "technology"],
    estimatedMinutes: 25,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
  {
    id: "training.risk-management",
    titleKey: "training.riskManagement.title",
    descriptionKey: "training.riskManagement.description",
    contentType: "book",
    productCodes: ["lro"],
    tags: ["risk", "management", "protection"],
    estimatedMinutes: 75,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
  {
    id: "training.international-contract-law",
    titleKey: "training.internationalContractLaw.title",
    descriptionKey: "training.internationalContractLaw.description",
    contentType: "video",
    productCodes: ["lro"],
    tags: ["international", "legal", "cross-border"],
    estimatedMinutes: 55,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
  {
    id: "training.contract-drafting-templates",
    titleKey: "training.contractDraftingTemplates.title",
    descriptionKey: "training.contractDraftingTemplates.description",
    contentType: "template",
    productCodes: ["lro"],
    tags: ["templates", "drafting", "examples"],
    downloadable: true,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
  {
    id: "training.compliance-regulatory",
    titleKey: "training.complianceRegulatory.title",
    descriptionKey: "training.complianceRegulatory.description",
    contentType: "article",
    productCodes: ["lro"],
    tags: ["compliance", "regulations", "legal"],
    estimatedMinutes: 40,
    authorName: "PactUS Pro",
    lifecycle: "available",
  },
];
