const EN: Record<string, string> = {
  "navigation.home": "Home",
  "navigation.lro": "LRO",
  "navigation.pfie": "PFIE",
  "navigation.scout": "Scout",
  "navigation.timeBilling": "Time & Billing",
  "navigation.experienceCenter": "Experience Center",
  "navigation.reportsAnalytics": "Reports & Analytics",
  "navigation.administration": "Administration",

  "lro.navigation.home": "Home",
  "lro.navigation.laborDocuments": "Labor Documents",
  "lro.navigation.bargainingUnits": "Bargaining Units",
  "lro.navigation.jobDescriptions": "Job Descriptions",
  "lro.navigation.unions": "Unions",
  "lro.navigation.grievances": "Grievances",
  "lro.navigation.compliance": "Compliance",
  "lro.navigation.externalSystems": "External Systems",
  "lro.navigation.dashboard": "Dashboard",
  "lro.navigation.inbox": "Inbox",
  "lro.navigation.analytics": "Analytics",
  "lro.navigation.documentWorkspace": "Document Workspace",
  "lro.navigation.negotiation": "Negotiation",
  "lro.navigation.intake": "Intake",
  "lro.navigation.approvals": "Approvals",
  "lro.navigation.reports": "Reports",
  "lro.navigation.admin": "Administration",
  "navigation.newContract": "New Contract",
  "navigation.eLearning": "E-Learning",
  "navigation.inbox": "Inbox",
  "navigation.analytics": "Analytics",
  "navigation.admin": "Administration",

  "pfie.navigation.home": "PFIE",
  "pfie.navigation.workspaces": "Workspaces",
  "pfie.navigation.uploadData": "Upload Data",
  "pfie.navigation.scenarios": "Scenarios",
  "pfie.navigation.savedScenarios": "Saved Scenarios",
  "pfie.navigation.results": "Results",
  "pfie.navigation.impactAnalysis": "Impact Analysis",
  "pfie.navigation.employeeAudit": "Employee Audit",
  "pfie.navigation.unionClassification": "Union Classification",
  "pfie.navigation.executiveIntelligence": "Executive Intelligence",
  "pfie.navigation.executiveReporting": "Executive Reporting",
  "pfie.navigation.demoCenter": "Demo Center",
  "pfie.navigation.commandCenter": "Command Center",
  "pfie.navigation.multiUnionPortfolio": "Multi-Union Portfolio",
  "pfie.navigation.portfolioCommandCenter": "Portfolio Command Center",
  "pfie.navigation.crossUnionSimulation": "Cross-Union Simulation",
  "pfie.navigation.knowledgeGraph": "Knowledge Graph",
  "pfie.navigation.billableTime": "Billable Time",
  "pfie.navigation.billableRates": "Billable Rates",
  "pfie.navigation.audit": "Audit",
  "pfie.navigation.reportCenter": "Report Center",
  "pfie.navigation.userGuide": "User Guide",
};

const ES: Record<string, string> = {
  "navigation.home": "Inicio",
  "navigation.lro": "LRO",
  "navigation.pfie": "PFIE",
  "navigation.scout": "Scout",
  "navigation.timeBilling": "Tiempo y Facturación",
  "navigation.experienceCenter": "Centro de Experiencia",
  "navigation.reportsAnalytics": "Reportes y Análisis",
  "navigation.administration": "Administración",
};

export function labelFor(
  key: string,
  language: "en" | "es",
): string {
  if (language === "es") return ES[key] ?? EN[key] ?? key;
  return EN[key] ?? key;
}
