import { ENTITLEMENTS } from "../entitlements";
import { PERMISSIONS } from "../permissions";
import type { ModuleManifest } from "../types";

export const LRO_MODULES: ModuleManifest[] = [
  {
    id: "lro.contracts",
    code: "contracts",
    product: "lro",
    titleKey: "modules.lro.contracts.title",
    descriptionKey: "modules.lro.contracts.description",
    routeBase: "/lro/contracts",
    iconKey: "contracts",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.contracts],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.contracts",
    trainingContext: "lro.contracts",
    supportContext: "lro.contracts",
  },
  {
    id: "lro.bargaining_units",
    code: "bargaining_units",
    product: "lro",
    titleKey: "modules.lro.bargainingUnits.title",
    descriptionKey: "modules.lro.bargainingUnits.description",
    routeBase: "/lro/bargaining-units",
    iconKey: "users",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.bargainingUnits],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.bargaining_units",
    trainingContext: "lro.bargaining_units",
    supportContext: "lro.bargaining_units",
  },
  {
    id: "lro.job_descriptions",
    code: "job_descriptions",
    product: "lro",
    titleKey: "modules.lro.jobDescriptions.title",
    descriptionKey: "modules.lro.jobDescriptions.description",
    routeBase: "/lro/job-descriptions",
    iconKey: "briefcase",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.jobDescriptions],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.job_descriptions",
    trainingContext: "lro.job_descriptions",
    supportContext: "lro.job_descriptions",
  },
  {
    id: "lro.grievances",
    code: "grievances",
    product: "lro",
    titleKey: "modules.lro.grievances.title",
    descriptionKey: "modules.lro.grievances.description",
    routeBase: "/lro/grievances",
    iconKey: "alert-circle",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.grievances],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.grievances",
    trainingContext: "lro.grievances",
    supportContext: "lro.grievances",
  },
  {
    id: "lro.arbitration",
    code: "arbitration",
    product: "lro",
    titleKey: "modules.lro.arbitration.title",
    descriptionKey: "modules.lro.arbitration.description",
    routeBase: "/lro/arbitration",
    iconKey: "scale",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.arbitration],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.arbitration",
    trainingContext: "lro.arbitration",
    supportContext: "lro.arbitration",
  },
  {
    id: "lro.negotiation",
    code: "negotiation",
    product: "lro",
    titleKey: "modules.lro.negotiation.title",
    descriptionKey: "modules.lro.negotiation.description",
    routeBase: "/lro/negotiation",
    iconKey: "handshake",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.negotiation],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.negotiation",
    trainingContext: "lro.negotiation",
    supportContext: "lro.negotiation",
  },
  {
    id: "lro.ai_negotiation_copilot",
    code: "ai_negotiation_copilot",
    product: "lro",
    titleKey: "modules.lro.aiNegotiationCopilot.title",
    descriptionKey: "modules.lro.aiNegotiationCopilot.description",
    routeBase: "/lro/ai-negotiation-copilot",
    iconKey: "sparkles",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.aiNegotiationCopilot],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "coming_soon",
    navigationItems: [],
    helpContext: "lro.ai_negotiation_copilot",
    trainingContext: "lro.ai_negotiation_copilot",
    supportContext: "lro.ai_negotiation_copilot",
  },
  {
    id: "lro.compliance",
    code: "compliance",
    product: "lro",
    titleKey: "modules.lro.compliance.title",
    descriptionKey: "modules.lro.compliance.description",
    routeBase: "/lro/compliance",
    iconKey: "shield-check",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.compliance],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.compliance",
    trainingContext: "lro.compliance",
    supportContext: "lro.compliance",
  },
  {
    id: "lro.reports",
    code: "reports",
    product: "lro",
    titleKey: "modules.lro.reports.title",
    descriptionKey: "modules.lro.reports.description",
    routeBase: "/lro/reports",
    iconKey: "chart",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.reports],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.reports",
    trainingContext: "lro.reports",
    supportContext: "lro.reports",
  },
  {
    id: "lro.external_systems",
    code: "external_systems",
    product: "lro",
    titleKey: "modules.lro.externalSystems.title",
    descriptionKey: "modules.lro.externalSystems.description",
    routeBase: "/lro/external-systems",
    iconKey: "plug",
    requiredEntitlements: [ENTITLEMENTS.product.lro, ENTITLEMENTS.lro.externalSystems],
    requiredPermissions: [PERMISSIONS.lro.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "lro.external_systems",
    trainingContext: "lro.external_systems",
    supportContext: "lro.external_systems",
  },
];
