import { ENTITLEMENTS } from "../entitlements";
import { PERMISSIONS } from "../permissions";
import type { ModuleManifest } from "../types";

export const PFIE_MODULES: ModuleManifest[] = [
  {
    id: "pfie.financial_modeling",
    code: "financial_modeling",
    product: "pfie",
    titleKey: "modules.pfie.financialModeling.title",
    descriptionKey: "modules.pfie.financialModeling.description",
    routeBase: "/pfie/financial-modeling",
    iconKey: "calculator",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.financialModeling],
    requiredPermissions: [PERMISSIONS.pfie.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.financial_modeling",
    trainingContext: "pfie.financial_modeling",
    supportContext: "pfie.financial_modeling",
  },
  {
    id: "pfie.scenarios",
    code: "scenarios",
    product: "pfie",
    titleKey: "modules.pfie.scenarios.title",
    descriptionKey: "modules.pfie.scenarios.description",
    routeBase: "/pfie/scenarios",
    iconKey: "git-branch",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.scenarios],
    requiredPermissions: [PERMISSIONS.pfie.runCalculation],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.scenarios",
    trainingContext: "pfie.scenarios",
    supportContext: "pfie.scenarios",
  },
  {
    id: "pfie.employee_cost_analytics",
    code: "employee_cost_analytics",
    product: "pfie",
    titleKey: "modules.pfie.employeeCostAnalytics.title",
    descriptionKey: "modules.pfie.employeeCostAnalytics.description",
    routeBase: "/pfie/employee-cost-analytics",
    iconKey: "users",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.employeeCostAnalytics],
    requiredPermissions: [PERMISSIONS.pfie.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.employee_cost_analytics",
    trainingContext: "pfie.employee_cost_analytics",
    supportContext: "pfie.employee_cost_analytics",
  },
  {
    id: "pfie.benefits",
    code: "benefits",
    product: "pfie",
    titleKey: "modules.pfie.benefits.title",
    descriptionKey: "modules.pfie.benefits.description",
    routeBase: "/pfie/benefits",
    iconKey: "heart-pulse",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.benefits],
    requiredPermissions: [PERMISSIONS.pfie.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.benefits",
    trainingContext: "pfie.benefits",
    supportContext: "pfie.benefits",
  },
  {
    id: "pfie.workforce",
    code: "workforce",
    product: "pfie",
    titleKey: "modules.pfie.workforce.title",
    descriptionKey: "modules.pfie.workforce.description",
    routeBase: "/pfie/workforce",
    iconKey: "building-2",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.workforce],
    requiredPermissions: [PERMISSIONS.pfie.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.workforce",
    trainingContext: "pfie.workforce",
    supportContext: "pfie.workforce",
  },
  {
    id: "pfie.cross_union_impact",
    code: "cross_union_impact",
    product: "pfie",
    titleKey: "modules.pfie.crossUnionImpact.title",
    descriptionKey: "modules.pfie.crossUnionImpact.description",
    routeBase: "/pfie/cross-union-impact",
    iconKey: "network",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.crossUnionImpact],
    requiredPermissions: [PERMISSIONS.pfie.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.cross_union_impact",
    trainingContext: "pfie.cross_union_impact",
    supportContext: "pfie.cross_union_impact",
  },
  {
    id: "pfie.forecasting",
    code: "forecasting",
    product: "pfie",
    titleKey: "modules.pfie.forecasting.title",
    descriptionKey: "modules.pfie.forecasting.description",
    routeBase: "/pfie/forecasting",
    iconKey: "trending-up",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.forecasting],
    requiredPermissions: [PERMISSIONS.pfie.runCalculation],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.forecasting",
    trainingContext: "pfie.forecasting",
    supportContext: "pfie.forecasting",
  },
  {
    id: "pfie.executive_dashboard",
    code: "executive_dashboard",
    product: "pfie",
    titleKey: "modules.pfie.executiveDashboard.title",
    descriptionKey: "modules.pfie.executiveDashboard.description",
    routeBase: "/pfie/executive-dashboard",
    iconKey: "layout-dashboard",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.executiveDashboard],
    requiredPermissions: [PERMISSIONS.pfie.viewPortfolioDashboard],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.executive_dashboard",
    trainingContext: "pfie.executive_dashboard",
    supportContext: "pfie.executive_dashboard",
  },
  {
    id: "pfie.reporting",
    code: "reporting",
    product: "pfie",
    titleKey: "modules.pfie.reporting.title",
    descriptionKey: "modules.pfie.reporting.description",
    routeBase: "/pfie/reporting",
    iconKey: "file-bar-chart",
    requiredEntitlements: [ENTITLEMENTS.product.pfie, ENTITLEMENTS.pfie.reporting],
    requiredPermissions: [PERMISSIONS.pfie.exportReport],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "pfie.reporting",
    trainingContext: "pfie.reporting",
    supportContext: "pfie.reporting",
  },
];
