import { ENTITLEMENTS } from "../entitlements";
import { PERMISSIONS } from "../permissions";
import type { ModuleManifest } from "../types";

export const SCOUT_MODULES: ModuleManifest[] = [
  {
    id: "scout.opportunity_search",
    code: "opportunity_search",
    product: "scout",
    titleKey: "modules.scout.opportunitySearch.title",
    descriptionKey: "modules.scout.opportunitySearch.description",
    routeBase: "/scout/opportunities",
    iconKey: "search",
    requiredEntitlements: [ENTITLEMENTS.product.scout, ENTITLEMENTS.scout.opportunitySearch],
    requiredPermissions: [PERMISSIONS.scout.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "scout.opportunity_search",
    trainingContext: "scout.opportunity_search",
    supportContext: "scout.opportunity_search",
  },
  {
    id: "scout.crawling",
    code: "crawling",
    product: "scout",
    titleKey: "modules.scout.crawling.title",
    descriptionKey: "modules.scout.crawling.description",
    routeBase: "/scout/crawling",
    iconKey: "radar",
    requiredEntitlements: [ENTITLEMENTS.product.scout, ENTITLEMENTS.scout.crawling],
    requiredPermissions: [PERMISSIONS.scout.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "scout.crawling",
    trainingContext: "scout.crawling",
    supportContext: "scout.crawling",
  },
  {
    id: "scout.entity_monitoring",
    code: "entity_monitoring",
    product: "scout",
    titleKey: "modules.scout.entityMonitoring.title",
    descriptionKey: "modules.scout.entityMonitoring.description",
    routeBase: "/scout/entities",
    iconKey: "eye",
    requiredEntitlements: [ENTITLEMENTS.product.scout, ENTITLEMENTS.scout.entityMonitoring],
    requiredPermissions: [PERMISSIONS.scout.manageEntities],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "scout.entity_monitoring",
    trainingContext: "scout.entity_monitoring",
    supportContext: "scout.entity_monitoring",
  },
  {
    id: "scout.alerts",
    code: "alerts",
    product: "scout",
    titleKey: "modules.scout.alerts.title",
    descriptionKey: "modules.scout.alerts.description",
    routeBase: "/scout/alerts",
    iconKey: "bell",
    requiredEntitlements: [ENTITLEMENTS.product.scout, ENTITLEMENTS.scout.alerts],
    requiredPermissions: [PERMISSIONS.scout.configureAlerts],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "scout.alerts",
    trainingContext: "scout.alerts",
    supportContext: "scout.alerts",
  },
  {
    id: "scout.competitive_intelligence",
    code: "competitive_intelligence",
    product: "scout",
    titleKey: "modules.scout.competitiveIntelligence.title",
    descriptionKey: "modules.scout.competitiveIntelligence.description",
    routeBase: "/scout/competitive-intelligence",
    iconKey: "activity",
    requiredEntitlements: [ENTITLEMENTS.product.scout, ENTITLEMENTS.scout.competitiveIntelligence],
    requiredPermissions: [PERMISSIONS.scout.view],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "scout.competitive_intelligence",
    trainingContext: "scout.competitive_intelligence",
    supportContext: "scout.competitive_intelligence",
  },
  {
    id: "scout.export",
    code: "export",
    product: "scout",
    titleKey: "modules.scout.export.title",
    descriptionKey: "modules.scout.export.description",
    routeBase: "/scout/export",
    iconKey: "download",
    requiredEntitlements: [ENTITLEMENTS.product.scout, ENTITLEMENTS.scout.export],
    requiredPermissions: [PERMISSIONS.scout.exportOpportunities],
    lifecycle: "available",
    navigationItems: [],
    helpContext: "scout.export",
    trainingContext: "scout.export",
    supportContext: "scout.export",
  },
];
