import type { TranslationCatalog } from "../types";

export const EN_US: TranslationCatalog = {
  "shell.search.aria": "Search PactUS Pro",
  "shell.search.placeholder": "Search PactUS Pro...",
  "shell.timer.aria": "Time and Billing timer",
  "shell.help.aria": "Contextual help",
  "shell.language.aria": "Language",
  "shell.navigation.global.aria": "Global navigation",
  "shell.navigation.expand": "Expand navigation",
  "shell.navigation.collapse": "Collapse navigation",
  "shell.brand.platform": "Central Platform",
  "navigation.home": "Home",
  "navigation.lro": "LRO",
  "navigation.pfie": "PFIE",
  "navigation.scout": "Scout",
  "navigation.timeBilling": "Time & Billing",
  "navigation.experienceCenter": "Experience Center",
  "navigation.reportsAnalytics": "Reports & Analytics",
  "navigation.administration": "Administration",
  "navigation.newContract": "New Contract",
  "navigation.eLearning": "E-Learning",
  "navigation.inbox": "Inbox",
  "navigation.analytics": "Analytics",
  "navigation.admin": "Administration",
  "navigation.group.general": "General",
  "navigation.group.workspace": "Workspace",
  "navigation.group.agreements": "Agreements & Documents",
  "navigation.group.workforce": "Workforce Governance",
  "navigation.group.cases": "Cases & Grievances",
  "navigation.group.governance": "Governance",
  "navigation.group.integrations": "Integrations",
  "navigation.group.analytics": "Analytics",
  "navigation.group.bargaining": "Bargaining & Negotiation",
  "navigation.group.operations": "Operations",
  "navigation.group.tiptap": "Collaborative Editor",
  "navigation.group.core": "Core",
  "navigation.group.workflow": "Workflow",
  "navigation.group.analysis": "Analysis",
  "navigation.group.executive": "Executive Intelligence",
  "navigation.group.training": "Training",
  "navigation.group.advanced": "Advanced Tools",
  "navigation.group.portfolio": "Portfolio Strategy",
  "navigation.group.administration": "Administration",
  "navigation.group.help": "Help",
  "lro.navigation.home": "Home",
  "lro.navigation.laborDocuments": "Labor Documents",
  "lro.navigation.bargainingUnits": "Bargaining Units",
  "lro.navigation.jobDescriptions": "Job Descriptions",
  "lro.navigation.unions": "Unions",
  "lro.navigation.grievances": "Grievances",
  "lro.navigation.compliance": "Compliance",
  "lro.navigation.externalSystems": "External Systems",
  "lro.navigation.dashboard": "Dashboard",
  "lro.navigation.inbox": "Inbox",
  "lro.navigation.analytics": "Analytics",
  "lro.navigation.documentWorkspace": "Document Workspace",
  "lro.navigation.negotiation": "Negotiation",
  "lro.navigation.intake": "Intake",
  "lro.navigation.approvals": "Approvals",
  "lro.navigation.reports": "Reports",
  "lro.navigation.admin": "Administration",
  "pfie.navigation.home": "PFIE",
  "pfie.navigation.workspaces": "Workspaces",
  "pfie.navigation.uploadData": "Upload Data",
  "pfie.navigation.scenarios": "Scenarios",
  "pfie.navigation.savedScenarios": "Saved Scenarios",
  "pfie.navigation.results": "Results",
  "pfie.navigation.impactAnalysis": "Impact Analysis",
  "pfie.navigation.employeeAudit": "Employee Audit",
  "pfie.navigation.unionClassification": "Union Classification",
  "pfie.navigation.executiveIntelligence": "Executive Intelligence",
  "pfie.navigation.executiveReporting": "Executive Reporting",
  "pfie.navigation.demoCenter": "Demo Center",
  "pfie.navigation.commandCenter": "Command Center",
  "pfie.navigation.multiUnionPortfolio": "Multi-Union Portfolio",
  "pfie.navigation.portfolioCommandCenter": "Portfolio Command Center",
  "pfie.navigation.crossUnionSimulation": "Cross-Union Simulation",
  "pfie.navigation.knowledgeGraph": "Knowledge Graph",
  "pfie.navigation.billableTime": "Billable Time",
  "pfie.navigation.billableRates": "Billable Rates",
  "pfie.navigation.audit": "Audit",
  "pfie.navigation.reportCenter": "Report Center",
  "pfie.navigation.userGuide": "User Guide",
};
