import type { TranslationCatalog } from "../types";

export const ES_US: TranslationCatalog = {
  "shell.search.aria": "Buscar en PactUS Pro",
  "shell.search.placeholder": "Buscar en PactUS Pro...",
  "shell.timer.aria": "Temporizador de tiempo y facturación",
  "shell.help.aria": "Ayuda contextual",
  "shell.language.aria": "Idioma",
  "shell.navigation.global.aria": "Navegación global",
  "shell.navigation.expand": "Expandir navegación",
  "shell.navigation.collapse": "Contraer navegación",
  "shell.brand.platform": "Plataforma Central",
  "navigation.home": "Inicio",
  "navigation.lro": "LRO",
  "navigation.pfie": "PFIE",
  "navigation.scout": "Scout",
  "navigation.timeBilling": "Tiempo y Facturación",
  "navigation.experienceCenter": "Centro de Experiencia",
  "navigation.reportsAnalytics": "Reportes y Análisis",
  "navigation.administration": "Administración",
  "navigation.newContract": "Nuevo Contrato",
  "navigation.eLearning": "Aprendizaje en Línea",
  "navigation.inbox": "Bandeja de Entrada",
  "navigation.analytics": "Análisis",
  "navigation.admin": "Administración",
  "navigation.group.general": "General",
  "navigation.group.workspace": "Espacio de Trabajo",
  "navigation.group.agreements": "Convenios y Documentos",
  "navigation.group.workforce": "Gobernanza de la Fuerza Laboral",
  "navigation.group.cases": "Casos y Quejas",
  "navigation.group.governance": "Gobernanza",
  "navigation.group.integrations": "Integraciones",
  "navigation.group.analytics": "Análisis",
  "navigation.group.bargaining": "Negociación Colectiva",
  "navigation.group.operations": "Operaciones",
  "navigation.group.tiptap": "Editor Colaborativo",
  "navigation.group.core": "Principal",
  "navigation.group.workflow": "Flujo de Trabajo",
  "navigation.group.analysis": "Análisis",
  "navigation.group.executive": "Inteligencia Ejecutiva",
  "navigation.group.training": "Capacitación",
  "navigation.group.advanced": "Herramientas Avanzadas",
  "navigation.group.portfolio": "Estrategia de Portafolio",
  "navigation.group.administration": "Administración",
  "navigation.group.help": "Ayuda",
  "lro.navigation.home": "Inicio",
  "lro.navigation.laborDocuments": "Documentos Laborales",
  "lro.navigation.bargainingUnits": "Unidades de Negociación",
  "lro.navigation.jobDescriptions": "Descripciones de Puestos",
  "lro.navigation.unions": "Sindicatos",
  "lro.navigation.grievances": "Quejas Laborales",
  "lro.navigation.compliance": "Cumplimiento",
  "lro.navigation.externalSystems": "Sistemas Externos",
  "lro.navigation.dashboard": "Panel",
  "lro.navigation.inbox": "Bandeja de Entrada",
  "lro.navigation.analytics": "Análisis",
  "lro.navigation.documentWorkspace": "Espacio de Documentos",
  "lro.navigation.negotiation": "Negociación",
  "lro.navigation.intake": "Ingreso",
  "lro.navigation.approvals": "Aprobaciones",
  "lro.navigation.reports": "Reportes",
  "lro.navigation.admin": "Administración",
  "pfie.navigation.home": "PFIE",
  "pfie.navigation.workspaces": "Espacios de Trabajo",
  "pfie.navigation.uploadData": "Cargar Datos",
  "pfie.navigation.scenarios": "Escenarios",
  "pfie.navigation.savedScenarios": "Escenarios Guardados",
  "pfie.navigation.results": "Resultados",
  "pfie.navigation.impactAnalysis": "Análisis de Impacto",
  "pfie.navigation.employeeAudit": "Auditoría de Costos de Empleados",
  "pfie.navigation.unionClassification": "Clasificación Sindical",
  "pfie.navigation.executiveIntelligence": "Inteligencia Ejecutiva",
  "pfie.navigation.executiveReporting": "Reportes Ejecutivos",
  "pfie.navigation.demoCenter": "Centro de Demostración",
  "pfie.navigation.commandCenter": "Centro de Comando",
  "pfie.navigation.multiUnionPortfolio": "Portafolio Multisindical",
  "pfie.navigation.portfolioCommandCenter": "Centro de Comando del Portafolio",
  "pfie.navigation.crossUnionSimulation": "Simulación Entre Sindicatos",
  "pfie.navigation.knowledgeGraph": "Gráfico de Conocimiento",
  "pfie.navigation.billableTime": "Tiempo Facturable",
  "pfie.navigation.billableRates": "Tarifas Facturables",
  "pfie.navigation.audit": "Auditoría",
  "pfie.navigation.reportCenter": "Centro de Reportes",
  "pfie.navigation.userGuide": "Guía del Usuario",
};
